language: python
python:
  - "3.6"
  - "3.7"

service: 
  - docker

# build docker image and run container
before_install:
  # The following 2 lines are commented out because
  # they are no longer needed. These were for the 
  # activity 2 tests
  # - docker build -t helloworld src/act2
  # - docker run -d -p 80:80 --name hw helloworld
  - docker-compose build src/HooliTube/webserver
  - docker-compose up -d

# commands to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - pytest tests/