version: "3"

services:
  services:
  web:
    build: .
    ports:
      - 80:80

  db:
    image: mariadb
    container_name: mariadb
    command: --max-allowed-packet=128MB
    restart: always
    volumes:
      - hoolitube:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: agoodpassword
      MYSQL_DATABASE: hoolitube